services:
  - type: web
    name: laravel-demo-wsgmed
    env: php
    buildCommand: |
      composer install --no-dev
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      php artisan migrate --force
      php artisan db:seed --force
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    autoDeploy: true
